remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: DETSTVO bot
description: For viewing a special content type, here are basic information about our policy.
show_downloads: false
