remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: DETSTVO bot
description: Before using or if you have any questions, please pay attention to our terms of use.
show_downloads: false
